plugins:
  - prettier
  - coffee
extends:
  - plugin:coffee/all
rules:
  no-unused-vars: &err
    - error
  no-undef: *err
  prettier/prettier: [error, {parser: coffeescript, pluginSearchDirs: [.]}]
  prefer-destructuring: [error, {object: true}]
  no-console: error
  coffee/no-unused-expressions: off
  coffee/no-magic-numbers: off
  coffee/no-implicit-coercion: off
env:
  node: true
  es6: true
