plugins:
  - prettier
  - coffee
extends:
  - plugin:coffee/all
rules:
  no-unused-vars: error
  no-undef: error
  prettier/prettier: [error, {parser: coffeescript, pluginSearchDirs: [.]}]
  prefer-destructuring: [error, {object: true}]
  no-console: error
  no-unreachable: error
env:
  node: true
