// Generated by CoffeeScript 2.5.1
(function() {
  module.exports = ['BigInt', 'BigIntConstructor', 'BigInt64Array', 'BigInt64ArrayConstructor', 'BigUint64Array', 'BigUint64ArrayConstructor', 'DataView'];

}).call(this);
