// Generated by CoffeeScript 2.5.1
(function() {
  module.exports = ['ActiveXObject', 'ITextWriter', 'TextStreamBase', 'TextStreamWriter', 'TextStreamReader', 'Enumerator', 'EnumeratorConstructor', 'VBArray', 'VBArrayConstructor', 'DateConstructor', 'Date'];

}).call(this);
